# Generated by Django 4.2.7 on 2023-12-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0008_alter_branch_schedule"),
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaristaNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Notice",
        ),
    ]
