# Generated by Django 4.2.7 on 2023-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0002_baristanotification_delete_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="baristanotification",
            name="order_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
