# Generated by Django 4.2.7 on 2023-12-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0003_baristanotification_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
