# Generated by Django 4.2.7 on 2023-12-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0004_clentnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="clentnotification",
            name="status",
            field=models.CharField(default="new", max_length=255),
        ),
    ]
