# Generated by Django 4.2.7 on 2023-12-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0006_adminnotification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminnotification",
            name="running_out_of",
        ),
        migrations.AddField(
            model_name="adminnotification",
            name="text",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
