# Generated by Django 4.2.7 on 2023-12-30 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0009_reminder_date_of_reminder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reminder",
            options={"ordering": ["-date_of_reminder"]},
        ),
    ]
