# Generated by Django 4.2.5 on 2023-09-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token_auth",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
