# Generated by Django 4.2.7 on 2023-11-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0006_branch_name_of_shop"),
        ("accounts", "0003_employeeschedule_employeeworkdays_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="branches.branch",
            ),
        ),
    ]
