# Generated by Django 4.2.5 on 2023-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
