image: docker:latest

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY_USER: "ulukman"
  CI_REGISTRY_PASSWORD: "AzisAzis05"
  CI_REGISTRY: "docker.io"
  CI_REGISTRY_IMAGE: "ulukman/backend:latest"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

test:
  stage: test
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker run --name django_test_container -d $CI_REGISTRY_IMAGE
    - docker exec django_test_container python manage.py test apps
