# Generated by Django 4.2.5 on 2023-10-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
