# Generated by Django 4.2.6 on 2023-10-25 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_customuser_first_name_customuser_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
