# Generated by Django 4.2.7 on 2023-12-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price_with_discount',
        ),
    ]
