# Generated by Django 4.2.7 on 2023-12-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordering", "0004_remove_orderitem_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="in_an_institution",
            field=models.BooleanField(default=False, verbose_name="In an institution"),
        ),
    ]
