# Generated by Django 4.2.7 on 2023-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordering", "0006_order_branch_orderitem_ready_made_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In progress"),
                    ("ready", "Ready"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                ],
                default="new",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
