# Generated by Django 4.2.7 on 2023-12-26 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ordering", "0009_orderitem_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order item",
                "verbose_name_plural": "Order items",
            },
        ),
    ]
