# Generated by Django 4.2.7 on 2023-11-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0003_ingredient_date_of_arrival_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
