# Generated by Django 4.2.7 on 2023-11-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0004_item_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
