# Generated by Django 4.2.7 on 2023-11-16 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0006_remove_readymadeproduct_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="category",
        ),
    ]
