# Generated by Django 4.2.7 on 2023-11-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0007_remove_ingredient_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="readymadeproduct",
            name="date_of_arrival",
            field=models.DateField(auto_now=True),
        ),
    ]
