# Generated by Django 4.2.7 on 2023-11-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0009_alter_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
