# Generated by Django 4.2.7 on 2023-11-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0010_alter_category_name_alter_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="readymadeproduct",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
