# Generated by Django 4.2.7 on 2023-11-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_alter_schedule_title'),
        ('storage', '0012_alter_readymadeproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='minimal_limit',
        ),
        migrations.CreateModel(
            name='MinimalLimitReached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.ingredient')),
            ],
        ),
    ]
