# Generated by Django 4.2.7 on 2023-12-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_remove_readymadeproduct_minimal_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableatthebranch',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_at_the_branch', to='storage.ingredient'),
        ),
        migrations.AlterField(
            model_name='minimallimitreached',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minimal_limit', to='storage.ingredient'),
        ),
        migrations.AlterField(
            model_name='minimallimitreached',
            name='ready_made_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minimal_limit', to='storage.readymadeproduct'),
        ),
    ]
