# Generated by Django 4.2.7 on 2023-12-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0015_alter_availableatthebranch_ingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="readymadeproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="storage.category",
            ),
        ),
        migrations.AddField(
            model_name="readymadeproduct",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="readymadeproduct",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
