# Generated by Django 4.2.7 on 2023-12-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0016_readymadeproduct_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readymadeproductavailableatthebranch",
            name="ready_made_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availables",
                to="storage.readymadeproduct",
            ),
        ),
    ]
