# Generated by Django 4.2.7 on 2023-11-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
