# Generated by Django 4.2.7 on 2023-11-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_rename_phone_branch_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
