# Generated by Django 4.2.7 on 2023-11-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='branches.schedule'),
        ),
        migrations.AlterField(
            model_name='workdays',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='branches.schedule'),
        ),
    ]
