# Generated by Django 4.2.7 on 2023-11-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0006_branch_name_of_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
