# Generated by Django 4.2.7 on 2023-12-04 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_alter_schedule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='branches.schedule'),
        ),
    ]
