# Generated by Django 4.2.7 on 2023-12-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0008_alter_branch_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="counts_of_tables",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
